# permissions for end users to view configmapsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: config-weaver-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-viewer-role
rules:
- apiGroups:
  - weaver.example.com
  resources:
  - configmapsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weaver.example.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
