# test with
# kubectl auth can-i --as system:serviceaccount:default:default create configmaps -n foo
#
#rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: foo-configmap-sync
  namespace: foo
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  # Funny, only on the final stretch to multitenancy
  # I've noticed that the role lacked a basic verb: get.
  # needed by core configmap sync mechanic!
  - get
  - list
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: foo-configmap-sync
  namespace: foo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foo-configmap-sync
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
