apiVersion: weaver.example.com/v1alpha1
kind: ConfigMapSync
metadata:
  labels:
    app.kubernetes.io/name: config-weaver-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-sample
spec:
  testNum: 42
  source:
    name: sync-me-cm
    namespace: default
  syncToNamespaces:
  - foo
---
# Source ConfigMap
apiVersion: v1
data:
  key1: hello
kind: ConfigMap
metadata:
  name: sync-me-cm
  namespace: default
